""" name, priority,essential, type, code,maximum,beforeAgrabruh"""
import random
from khenum import itemType
def lowPriceRandom():
    return random.randint(200, 400)
def mediumPriceRandom():
    return random.randint(500, 1000)
def highPriceRandom():
    return random.randint(1000, 1500)
def ultraHighPriceRandom():
    return random.randint(1500, 2500)
def RandomPriceRandom():
    return random.randint(120, 2500)


currentType = itemType.Item
item_table = {
    'Potion':(False, False, currentType,  0x1,-1,False,random.randint(100,200)),
    'Hi-Potion':(False, False, currentType, 0x2,-1,False,random.randint(100,200)),
    'Ether':(False, False, currentType, 0x3,-1,False,random.randint(100,200)),
    'Elixir':(False, False, currentType, 0x4,-1,False,random.randint(100,200)),
    'Mega-Potion':(False, False, currentType, 0x5,-1,False,random.randint(100,200)),
    'Mega-Ether':(False, False, currentType, 0x6,-1,False,random.randint(100,200)),
    'Megalixir':(False, False, currentType, 0x7,-1,False,random.randint(100,200)),
    'Tent':(False, False, currentType, 0x83,-1,False,random.randint(100,200)),
    'Drive Recovery':(False, False, currentType, 0x112,-1,False,random.randint(500,1000)),
    'High Drive Recovery':(False, False, currentType, 0x113,-1,False,random.randint(500,1000)),
    'Power Boost':(False, False, currentType, 0x114,-1,False,random.randint(500,1000)),
    'Magic Boost':(False, False, currentType, 0x115,-1,False,random.randint(500,1000)),
    'Defense Boost':(False, False, currentType, 0x116,-1,False,random.randint(500,1000)),
    'AP Boost':(True, False, currentType, 0x117,52,False,random.randint(500,1000)), #52 is the amount you get in a single playthrough
}
currentType = itemType.Equipment
soraEquipment_table = {
    #'Kingdom Key'      :(    True,    False,    currentType,   0x29,   1),
    'Oathkeeper'      :(    True,    False,    currentType,   0x2A,   1),
    'Oblivion'        :(    True,    False,    currentType,   0x2B,   1),
    'Star Seeker'     :(    True,    False,    currentType,   0x1E0,   1),
    'Hidden Dragon'   :(    True,    False,    currentType,   0x1E1,   1),
    'Hero\'s Crest'   :(    True,    False,    currentType,   0x1E4,   1),
    'Monochrome'      :(    True,    False,    currentType,   0x1E5,   1),
    'Follow the Wind' :(    True,    False,    currentType,   0x1E6,   1),
    'Circle of Life'  :(    True,    False,    currentType,   0x1E7,   1),
    'Photon Debugger' :(    True,    False,    currentType,   0x1E8,   1),
    'Gull Wing'       :(    True,    False,    currentType,   0x1E9,   1),
    'Rumbling Rose'   :(    True,    False,    currentType,   0x1EA,   1),
    'Guardian Soul'   :(    True,    False,    currentType,   0x1EB,   1),
    'Wishing Lamp'    :(    True,    False,    currentType,   0x1EC,   1),
    'Decisive Pumpkin':(    True,    False,    currentType,   0x1ED,   1),
    'Sweet Memories'  :(    True,    False,    currentType,   0x1EF,   1),
    'Mysterious Abyss':(    True,    False,    currentType,   0x1F0,   1),
    'Sleeping Lion'   :(    True,    False,    currentType,   0x1EE,   1),
    'Bond of Flame'   :(    True,    False,    currentType,   0x1F2,   1),
    'Two Become One'  :(    True,    False,    currentType,   0x21F,   1),
    'Fatal Crest'     :(    True,    False,    currentType,   0x1F1,   1),
    'Fenrir'          :(    True,    False,    currentType,   0x1F3,   1),
    #'Ultima Weapon'          :(    True,    False,    currentType,   0x1F4,   1),
}
donaldEquipment_table = {
    'Hammer Staff' 		:(    False,    False,    currentType, 0x94,    1,False,RandomPriceRandom()),
    'Victory Bell'		:(    False,    False,    currentType, 0x95,    1,False,RandomPriceRandom()),
    'Comet Staff' 		:(    False,    False,    currentType, 0x97,   1,False,RandomPriceRandom()),
    'Lord\'s Broom' 	:(    False,    False,    currentType, 0x98,   1,False,RandomPriceRandom()),
    'Wisdom Wand' 		:(    False,    False,    currentType, 0x99,   1,False,RandomPriceRandom()),
    'Meteor Staff'      :(    False,    False,    currentType, 0x96,   1,False,RandomPriceRandom()),
    'Rising Dragon'     :(    False,    False,    currentType, 0x9A,   1,False,RandomPriceRandom()),
    'Shaman\'s Relic'   :(    False,    False,    currentType, 0x9C,   1,False,RandomPriceRandom()),
    'Shaman\'s Relic+'	:(    False,    False,    currentType, 0x258,   1,False,RandomPriceRandom()),
    'Nobody Lance'      :(    False,    False,    currentType, 0x9B,   1,False,RandomPriceRandom()),
    'Centurion'         :(    False,    False,    currentType, 0x221,   1,False,RandomPriceRandom()),
    'Centurion+'        :(    False,    False,    currentType, 0x222,   1,False,RandomPriceRandom()),
    'Save The Queen'    :(    False,    False,    currentType, 0x1E2,   1,False,RandomPriceRandom()),
    'Save the Queen+' 	:(    False,    False,    currentType, 0x1F7,   1,False,RandomPriceRandom()),
    'Plain Mushroom'	:(    False,    False,    currentType, 0x223,   1,False,RandomPriceRandom()),
    'Plain Mushroom+' 	:(    False,    False,    currentType, 0x224,   1,False,RandomPriceRandom()),
    'Precious Mushroom'	:(    False,    False,    currentType, 0x225,   1,False,RandomPriceRandom()),
    'Precious Mushroom+':(    False,    False,    currentType, 0x226,   1,False,RandomPriceRandom()),
    'Premium Mushroom' 	:(    False,    False,    currentType, 0x227,   1,False,RandomPriceRandom()),
}
goofyEquipment_table = {
    'Adamant Shield' 	:(    False,    False,    currentType, 0x08B,   1,False,RandomPriceRandom()),
    'Chain Shield' 		:(    False,    False,    currentType, 0x08C,   1,False,RandomPriceRandom()),
    'Falling Star' 		:(    False,    False,    currentType, 0x08E,  1,False,RandomPriceRandom()),
    'Dream Cloud' 		:(    False,    False,    currentType, 0x08F,  1,False,RandomPriceRandom()),
    'Knight Defender' 	:(    False,    False,    currentType, 0x090,  1,False,RandomPriceRandom()),
    'Ogre Shield'       :(    False,    False,    currentType, 0x08D,  1,False,RandomPriceRandom()),
    'Genji Shield'      :(    False,    False,    currentType, 0x091,  1,False,RandomPriceRandom()),
    'Akashic Record' 	:(    False,    False,    currentType, 0x092,  1,False,RandomPriceRandom()),
    'Akashic Record+'  	:(    False,    False,    currentType, 0x259,   1,False,RandomPriceRandom()),
    'Nobody Guard' 		:(    False,    False,    currentType, 0x093,  1,False,RandomPriceRandom()),
    'Frozen Pride' 		:(    False,    False,    currentType, 0x228,   1,False,RandomPriceRandom()),
    'Frozen Pride+'     :(    False,    False,    currentType, 0x229,   1,False,RandomPriceRandom()),
    'Save The King' 	:(    False,    False,    currentType, 0x1E3,   1,False,RandomPriceRandom()),
    'Save the King+' 	:(    False,    False,    currentType, 0x1F8,   1,False,RandomPriceRandom()),
    'Joyous Mushroom' 	:(    False,    False,    currentType, 0x22A,   1,False,RandomPriceRandom()),
    'Joyous Mushroom+' 	:(    False,    False,    currentType, 0x22B,   1,False,RandomPriceRandom()),
    'Majestic Mushroom' :(    False,    False,    currentType, 0x22C,   1,False,RandomPriceRandom()),
    'Majestic Mushroom+':(    False,    False,    currentType, 0x22D,   1,False,RandomPriceRandom()),
    'Ultimate Mushroom' :(    False,    False,    currentType, 0x22E,   1,False,RandomPriceRandom()),
}
currentType = itemType.Armor
armor_table = {
    'Elven Bandanna'   :(    False,    False,    currentType, 0x043,    2,False,lowPriceRandom()),
    'Divine Bandanna'  :(    False,    False,    currentType, 0x044,    2,False,lowPriceRandom()),
    'Protect Belt'     :(    False,    False,    currentType, 0x04E,    2,False,lowPriceRandom()),
    'Gaia Belt'        :(    False,    False,    currentType, 0x04F,    2,False,lowPriceRandom()),
    'Power Band'       :(    False,    False,    currentType, 0x045,    2,False,lowPriceRandom()),
    'Buster Band'      :(    False,    False,    currentType, 0x046,    2,False,lowPriceRandom()),
    'Cosmic Belt'      :(    False,    False,    currentType, 0x06F,    2,False,lowPriceRandom()),
    'Fire Bangle'      :(    False,    False,    currentType, 0x0AD,    2,False,lowPriceRandom()),
    'Fira Bangle'      :(    False,    False,    currentType, 0x0AE,    2,False,lowPriceRandom()),
    'Firaga Bangle'    :(    False,    False,    currentType, 0x0C5,    2,False,lowPriceRandom()),
    'Firagun Bangle'   :(    False,    False,    currentType, 0x11C,    2,False,lowPriceRandom()),
    'Blizzard Armlet'  :(    False,    False,    currentType, 0x11E,    2,False,lowPriceRandom()),
    'Blizzara Armlet'  :(    False,    False,    currentType, 0x11F,    2,False,lowPriceRandom()),
    'Blizzaga Armlet'  :(    False,    False,    currentType, 0x120,    2,False,lowPriceRandom()),
    'Blizzagun Armlet' :(    False,    False,    currentType, 0x121,    2,False,lowPriceRandom()),
    'Thunder Trinket'  :(    False,    False,    currentType, 0x123,    2,False,lowPriceRandom()),
    'Thundara Trinket' :(    False,    False,    currentType, 0x124,    2,False,lowPriceRandom()),
    'Thundaga Trinket' :(    False,    False,    currentType, 0x125,    2,False,mediumPriceRandom()),
    'Thundagun Trinket':(    False,    False,    currentType, 0x126,    2,False,highPriceRandom()),
    'Shock Charm'      :(    False,    False,    currentType, 0x084,    2,False,mediumPriceRandom()),
    'Shock Charm+'     :(    False,    False,    currentType, 0x085,    2,False,highPriceRandom()),
    'Shadow Anklet'    :(    False,    False,    currentType, 0x128,    2,False,mediumPriceRandom()),
    'Dark Anklet'      :(    False,    False,    currentType, 0x129,    2,False,mediumPriceRandom()),
    'Midnight Anklet'  :(    False,    False,    currentType, 0x12A,    2,False,mediumPriceRandom()),
    'Chaos Anklet'     :(    False,    False,    currentType, 0x12B,    2,False,mediumPriceRandom()),
    'Champion Belt'    :(    False,    False,    currentType, 0x131,    2,False,mediumPriceRandom()),
    'Abas Chain'       :(    False,    False,    currentType, 0x12D,    2,False,mediumPriceRandom()),
    'Aegis Chain'      :(    False,    False,    currentType, 0x12E,    2,False,mediumPriceRandom()),
    'Acrisius'         :(    False,    False,    currentType, 0x12F,    2,False,mediumPriceRandom()),
    'Acrisius+'        :(    False,    False,    currentType, 0x133,    2,False,mediumPriceRandom()),
    'Cosmic Chain'     :(    False,    False,    currentType, 0x134,    2,False,mediumPriceRandom()),
    'Petit Ribbon'     :(    False,    False,    currentType, 0x132,    1,False,mediumPriceRandom()),
    'Ribbon'           :(    False,    False,    currentType, 0x130,    1,False,highPriceRandom()),
    'Grand Ribbon'     :(    False,    False,    currentType, 0x09D,    random.randint(0,1),False,ultraHighPriceRandom()), #Give random chance to get grand ribbon in game
}
currentType = itemType.Accessory
accessory_table = {
    'Ability Ring'      :(    False,    False,    currentType, 0x008,    2,False,lowPriceRandom()),
    'Engineer\'s Ring'  :(    False,    False,    currentType, 0x009,    2,False,lowPriceRandom()),
    'Technician\'s Ring':(    False,    False,    currentType, 0x00A,    2,False,lowPriceRandom()),
    'Skill Ring'        :(    False,    False,    currentType, 0x026,    2,False,lowPriceRandom()),
    'Skillful Ring'     :(    False,    False,    currentType, 0x027,    2,False,lowPriceRandom()),
    'Expert\'s Ring'    :(    False,    False,    currentType, 0x00B,    2,False,lowPriceRandom()),
    'Master\'s Ring'    :(    False,    False,    currentType, 0x022,    2,False,lowPriceRandom()),
    'Cosmic Ring'       :(    False,    False,    currentType, 0x034,    2,False,lowPriceRandom()),
    'Executive\'s Ring' :(    False,    False,    currentType, 0x257,    2,False,lowPriceRandom()),
    'Sardonyx Ring'     :(    False,    False,    currentType, 0x00C,    2,False,lowPriceRandom()),
    'Tourmaline Ring'   :(    False,    False,    currentType, 0x00D,    2,False,lowPriceRandom()),
    'Aquamarine Ring'   :(    False,    False,    currentType, 0x00E,    2,False,lowPriceRandom()),
    'Garnet Ring'       :(    False,    False,    currentType, 0x00F,    2,False,lowPriceRandom()),
    'Diamond Ring'      :(    False,    False,    currentType, 0x010,    2,False,lowPriceRandom()),
    'Silver Ring'       :(    False,    False,    currentType, 0x011,    2,False,lowPriceRandom()),
    'Gold Ring'         :(    False,    False,    currentType, 0x012,    2,False,lowPriceRandom()),
    'Platinum Ring'     :(    False,    False,    currentType, 0x013,    2,False,lowPriceRandom()),
    'Mythril Ring'      :(    False,    False,    currentType, 0x014,    2,False,lowPriceRandom()),
    'Orichalcum Ring'   :(    False,    False,    currentType, 0x01C,    2,False,mediumPriceRandom()),
    'Soldier Earring'   :(    False,    False,    currentType, 0x028,    2,False,mediumPriceRandom()),
    'Fencer Earring'    :(    False,    False,    currentType, 0x02E,    2,False,mediumPriceRandom()),
    'Mage Earring'      :(    False,    False,    currentType, 0x02F,    2,False,mediumPriceRandom()),
    'Slayer Earring'    :(    False,    False,    currentType, 0x030,    2,False,mediumPriceRandom()),
    'Medal'             :(    False,    False,    currentType, 0x035,    2,False,mediumPriceRandom()),
    'Moon Amulet'       :(    False,    False,    currentType, 0x023,    2,False,mediumPriceRandom()),
    'Star Charm'        :(    False,    False,    currentType, 0x024,    2,False,mediumPriceRandom()),
    'Cosmic Arts'       :(    False,    False,    currentType, 0x038,    2,False,mediumPriceRandom()),
    'Shadow Archive'    :(    False,    False,    currentType, 0x039,    2,False,mediumPriceRandom()),
    'Shadow Archive+'   :(    False,    False,    currentType, 0x03A,    2,False,ultraHighPriceRandom()),
    'Full Bloom'        :(    False,    False,    currentType, 0x040,    2,False,mediumPriceRandom()),
    'Full Bloom+'       :(    False,    False,    currentType, 0x042,    2,False,ultraHighPriceRandom()),
    'Draw Ring'         :(    False,    False,    currentType, 0x041,    2,False,ultraHighPriceRandom()),
    'Lucky Ring'        :(    False,    False,    currentType, 0x03F,    2,False,ultraHighPriceRandom()),
}
currentType = itemType.Recipe
recipe_table = {
    'Mega Recipe'             :(    True,    False,    currentType, 0x17E,    1),
    'Star Recipe'             :(    True,    False,    currentType, 0x1C1,    1),
    'Recovery Recipe'         :(    True,    False,    currentType, 0x1C2,    1),
    'Skill Recipe'            :(    True,    False,    currentType, 0x1C3,    1),
    'Guard Recipe'            :(    True,    False,    currentType, 0x1C4,    1),
    'Road to Discovery'       :(    True,    False,    currentType, 0x1D0,    1),
    'Strength Beyond Strength':(    True,    False,    currentType, 0x1D1,    1),
    'Book of Shadows'         :(    True,    False,    currentType, 0x1D2,    1),
    'Cloaked Thunder'         :(    True,    False,    currentType, 0x1D3,    1),
    'Eternal Blossom'         :(    True,    False,    currentType, 0x1D4,    1),
    'Rare Document'           :(    True,    False,    currentType, 0x1D5,    1),
    'Style Recipe'            :(    True,    False,    currentType, 0x1DB,    1),
    'Moon Recipe'             :(    True,    False,    currentType, 0x1DC,    1),
    'Queen Recipe'            :(    True,    False,    currentType, 0x1DD,    1),
    'King Recipe'             :(    True,    False,    currentType, 0x1DE,    1),
    'Ultimate Recipe'         :(    True,    False,    currentType, 0x1DF,    1),
}
currentType = itemType.KeyItem
keyitem_table = {
    'Proof of Connection'       :(    True,    False,    currentType, 0x251,    1),
    'Proof of Nonexistence'     :(    True,    False,    currentType, 0x252,    1),
    'Proof of Peace'            :(    True,    False,    currentType, 0x253,    1),
    'Torn Pages'                :(    True,    True,     currentType, 0x020,    5),
    'Munny Pouch (Olette)'      :(    True,    False,    currentType, 0x16A,    1),
    'Munny Pouch (Mickey)'      :(    True,    False,    currentType, 0x217,    1),
    'Crystal Orb'               :(    True,    False,    currentType, 0x16B,    1),
    #'Seifer\'s Trophy'          :(    True,    False,    currentType, 0x16C,    1),
    'Tournament Poster'         :(    True,    False,    currentType, 0x16D,    1),
    'Poster'                    :(    True,    False,    currentType, 0x16E,    1),
    'Letter'                    :(    True,    False,    currentType, 0x16F,    1),
    'Namine\'s Sketches'        :(    True,    False,    currentType, 0x170,    1),
    'Membership Card'           :(    True,    False,    currentType, 0x171,    1),
    'Olympus Stone'             :(    True,    False,    currentType, 0x172,    1),
    'Auron\'s Statue'           :(    True,    False,    currentType, 0x173,    1),
    'Cursed Medallion'          :(    True,    False,    currentType, 0x174,    1),
    'Present'                   :(    True,    False,    currentType, 0x175,    1),
    'Decoy Presents'            :(    True,    False,    currentType, 0x176,    1),
    'Ice Cream'                 :(    True,    False,    currentType, 0x177,    1),
    'Picture'                   :(    True,    False,    currentType, 0x178,    1),
    'Promise Charm'             :(    True,    False,    currentType, 0x20C,    1),
    #'Hades Cup Trophy'          :(    True,    False,    currentType, 0x219,    1),
    #'"The Struggle" Trophy'     :(    True,    False,    currentType, 0x21A,    1),
    'Secret Ansem\'s Report 1'  :(    True,    False,    currentType, 0x0E2,    1),
    'Secret Ansem\'s Report 2'  :(    True,    False,    currentType, 0x0E3,    1),
    'Secret Ansem\'s Report 3'  :(    True,    False,    currentType, 0x0E4,    1),
    'Secret Ansem\'s Report 4'  :(    True,    False,    currentType, 0x0E5,    1),
    'Secret Ansem\'s Report 5'  :(    True,    False,    currentType, 0x0E6,    1),
    'Secret Ansem\'s Report 6'  :(    True,    False,    currentType, 0x0E7,    1),
    'Secret Ansem\'s Report 7'  :(    True,    False,    currentType, 0x0E8,    1),
    'Secret Ansem\'s Report 8'  :(    True,    False,    currentType, 0x0E9,    1),
    'Secret Ansem\'s Report 9'  :(    True,    False,    currentType, 0x0EA,    1),
    'Secret Ansem\'s Report 10' :(    True,    False,    currentType, 0x0EB,    1),
    'Secret Ansem\'s Report 11' :(    True,    False,    currentType, 0x0EC,    1),
    'Secret Ansem\'s Report 12' :(    True,    False,    currentType, 0x0ED,    1),
    'Secret Ansem\'s Report 13' :(    True,    False,    currentType, 0x0EE,    1),
}
currentType = itemType.Synthesis
synthesis_table = {
    'Blazing Shard'      :(    False,    False,    currentType, 0x13D,    13,False, mediumPriceRandom()),
    'Blazing Stone'      :(    False,    False,    currentType, 0x13E,    13,False, mediumPriceRandom()),
    'Blazing Gem'        :(    False,    False,    currentType, 0x13F,    13,False, mediumPriceRandom()),
    'Blazing Crystal'    :(    False,    False,    currentType, 0x140,    13,False, mediumPriceRandom()),
    'Frost Shard'        :(    False,    False,    currentType, 0x17A,    13,False, mediumPriceRandom()),
    'Frost Stone'        :(    False,    False,    currentType, 0x17B,    13,False, mediumPriceRandom()),
    'Frost Gem'          :(    False,    False,    currentType, 0x17C,    13,False, mediumPriceRandom()),
    'Frost Crystal'      :(    False,    False,    currentType, 0x17D,    13,False, mediumPriceRandom()),
    'Lightning Shard'    :(    False,    False,    currentType, 0x145,    13,False, mediumPriceRandom()),
    'Lightning Stone'    :(    False,    False,    currentType, 0x146,    13,False, mediumPriceRandom()),
    'Lightning Gem'      :(    False,    False,    currentType, 0x147,    13,False, mediumPriceRandom()),
    'Lightning Crystal'  :(    False,    False,    currentType, 0x148,    13,False, mediumPriceRandom()),
    'Lucid Shard'        :(    False,    False,    currentType, 0x14D,    13,False, mediumPriceRandom()),
    'Lucid Stone'        :(    False,    False,    currentType, 0x14E,    13,False, mediumPriceRandom()),
    'Lucid Gem'          :(    False,    False,    currentType, 0x14F,    13,False, mediumPriceRandom()),
    'Lucid Crystal'      :(    False,    False,    currentType, 0x150,    13,False, mediumPriceRandom()),
    'Power Shard'        :(    False,    False,    currentType, 0x149,    13,False, mediumPriceRandom()),
    'Power Stone'        :(    False,    False,    currentType, 0x14A,    13,False, mediumPriceRandom()),
    'Power Gem'          :(    False,    False,    currentType, 0x14B,    13,False, mediumPriceRandom()),
    'Power Crystal'      :(    False,    False,    currentType, 0x14C,    13,False, mediumPriceRandom()),
    'Dark Shard'         :(    False,    False,    currentType, 0x118,    13,False, mediumPriceRandom()),
    'Dark Stone'         :(    False,    False,    currentType, 0x119,    13,False, mediumPriceRandom()),
    'Dark Gem'           :(    False,    False,    currentType, 0x11A,    13,False, mediumPriceRandom()),
    'Dark Crystal'       :(    False,    False,    currentType, 0x11B,    13,False, mediumPriceRandom()),
    'Dense Shard'        :(    False,    False,    currentType, 0x151,    13,False, mediumPriceRandom()),
    'Dense Stone'        :(    False,    False,    currentType, 0x152,    13,False, mediumPriceRandom()),
    'Dense Gem'          :(    False,    False,    currentType, 0x153,    13,False, mediumPriceRandom()),
    'Dense Crystal'      :(    False,    False,    currentType, 0x154,    13,False, mediumPriceRandom()),
    'Twilight Shard'     :(    False,    False,    currentType, 0x155,    13,False, mediumPriceRandom()),
    'Twilight Stone'     :(    False,    False,    currentType, 0x156,    13,False, mediumPriceRandom()),
    'Twilight Gem'       :(    False,    False,    currentType, 0x157,    13,False, mediumPriceRandom()),
    'Twilight Crystal'   :(    False,    False,    currentType, 0x158,    13,False, mediumPriceRandom()),
    'Mythril Shard'      :(    False,    False,    currentType, 0x159,    13,False, mediumPriceRandom()),
    'Mythril Stone'      :(    False,    False,    currentType, 0x15A,    13,False, mediumPriceRandom()),
    'Mythril Gem'        :(    False,    False,    currentType, 0x15B,    13,False, mediumPriceRandom()),
    'Mythril Crystal'    :(    False,    False,    currentType, 0x15C,    13,False, mediumPriceRandom()),
    'Remembrance Shard'  :(    False,    False,    currentType, 0x240,    13,False, mediumPriceRandom()),
    'Remembrance Stone'  :(    False,    False,    currentType, 0x241,    13,False, mediumPriceRandom()),
    'Remembrance Gem'    :(    False,    False,    currentType, 0x242,    13,False, mediumPriceRandom()),
    'Remembrance Crystal':(    False,    False,    currentType, 0x243,    13,False, mediumPriceRandom()),
    'Tranquility Shard'  :(    False,    False,    currentType, 0x244,    13,False, mediumPriceRandom()),
    'Tranquility Stone'  :(    False,    False,    currentType, 0x245,    13,False, mediumPriceRandom()),
    'Tranquility Gem'    :(    False,    False,    currentType, 0x246,    13,False, mediumPriceRandom()),
    'Tranquility Crystal':(    False,    False,    currentType, 0x247,    13,False, mediumPriceRandom()),
    'Bright Shard'       :(    False,    False,    currentType, 0x15D,    13,False, mediumPriceRandom()),
    'Bright Stone'       :(    False,    False,    currentType, 0x15E,    13,False, mediumPriceRandom()),
    'Bright Gem'         :(    False,    False,    currentType, 0x15F,    13,False, mediumPriceRandom()),
    'Bright Crystal'     :(    False,    False,    currentType, 0x160,    13,False, mediumPriceRandom()),
    'Energy Shard'       :(    False,    False,    currentType, 0x161,    13,False, mediumPriceRandom()),
    'Energy Stone'       :(    False,    False,    currentType, 0x162,    13,False, mediumPriceRandom()),
    'Energy Gem'         :(    False,    False,    currentType, 0x163,    13,False, mediumPriceRandom()),
    'Energy Crystal'     :(    False,    False,    currentType, 0x164,    13,False, mediumPriceRandom()),
    'Serenity Shard'     :(    False,    False,    currentType, 0x165,    13,False, mediumPriceRandom()),
    'Serenity Stone'     :(    False,    False,    currentType, 0x166,    13,False, mediumPriceRandom()),
    'Serenity Gem'       :(    False,    False,    currentType, 0x167,    13,False, mediumPriceRandom()),
    'Serenity Crystal'   :(    False,    False,    currentType, 0x168,    13,False, mediumPriceRandom()),
    'Lost Illusion'      :(    True,    False,    currentType, 0x248,     2,False, random.randint(1500,2000)),
    'Manifest Illusion'  :(    True,    False,    currentType, 0x249,     2,False, random.randint(1500,2000)),
    'Orichalcum'         :(    True,    False,    currentType, 0x179,     1,False, random.randint(1500,3000)),
    'Orichalcum+'        :(    True,    False,    currentType, 0x169,     6,False, random.randint(1500,3000)),
}
currentType = itemType.Magic
magic_table = {
    'Fire Element'          :(    True,    True,    currentType, 0x0015,    2),
    'Blizzard Element'      :(    True,    True,    currentType, 0x0016,    2),
    'Thunder Element'       :(    True,    True,    currentType, 0x0017,    2),
    'Fire Element(AgrabahPreReq)'          :(    True,    True,    currentType, 0x0015,    1,True),
    'Blizzard Element(AgrabahPreReq)'      :(    True,    True,    currentType, 0x0016,    1,True),
    'Thunder Element(AgrabahPreReq)'       :(    True,    True,    currentType, 0x0017,    1,True),
    'Cure Element'          :(    True,    True,    currentType, 0x018,    3),
    'Magnet Element'        :(    True,    True,    currentType, 0x057,    3),
    'Reflect Element'       :(    True,    True,    currentType, 0x058,    3),
}
currentType = itemType.Drives
drive_table = {
    'Valor Form'       :(    True,    True,    currentType,     0x01A,   1),
    'Wisdom Form'      :(    True,    True,    currentType,     0x01B,   1),
    'Limit Form'        :(    True,    True,    currentType,    0x233,    1),
    'Master Form'       :(    True,    True,    currentType,    0x01F,    1),
    'Final Form'        :(    True,    True,    currentType,    0x01D,    1),
}
currentType = itemType.Summons
summon_table = {
    'Baseball Charm'       :(    True,    False,    currentType,     0x17F,  1),
    'Lamp Charm    '      :(    True,      False,    currentType,    0x09F,   1),
    'Ukulele Charm'         :(    True,   False,    currentType,    0x019,  1),
    'Feather Charm '       :(    True,    False,    currentType,    0x0A0,  1),
}
currentType = itemType.Maps
maps_table = {
    'Tower Map'       :(    True,    False,    currentType,     0x215,  1),
    'Twilight Town Map'       :(    True,    False,    currentType,     0x0FF,  1),
    'Mansion Map'       :(    True,    False,    currentType,     0x214,  1),
    'Castle Perimeter Map'       :(    True,    False,    currentType,     0x201,  1),
   'The Great Maw Map'        :(    True,    False,    currentType,     0x202,  1),
    'Marketplace Map'       :(    True,    False,    currentType,     0x0FD,  1),
    'Dark Remembrance Map'       :(    True,    False,    currentType,     0x24A,  1),
    'Depths of Remembrance Map'       :(    True,    False,    currentType,     0x24E,  1),
    'Garden of Assemblage Map'       :(    True,    False,    currentType,     0x250,  1),
    'Castle Map'       :(    True,    False,    currentType,     0x05A,  1),
    'Basement Map'       :(    True,    False,    currentType,     0x05B,  1),
    'Castle Walls Map'       :(    True,    False,    currentType,     0x05C,  1),
    'Underworld Map'       :(    True,    False,    currentType,     0x087,  1),
    'Caverns Map'       :(    True,    False,    currentType,     0x088,  1),
    'Coliseum Map'       :(    True,    False,    currentType,     0x086,  1),
    'Cave of Wonders Map'       :(    True,    False,    currentType,     0x079,  1),
    'Ruins Map'       :(    True,    False,    currentType,     0x07A,  1),
    'Agrabah Map'       :(    True,    False,    currentType,     0x078,  1),
    'Palace Map'       :(    True,    False,    currentType,     0x082,  1),
    'Encampment Area Map'       :(    True,    False,    currentType,     0x070,  1),
    'Village Area Map'       :(    True,    False,    currentType,     0x071,  1),
    '100 Acre Wood Map'       :(    True,    False,    currentType,     0x07D,  1),
    'Spooky Cave Map'       :(    True,    False,    currentType,     0x081,  1),
    'Savannah Map'       :(    True,    False,    currentType,     0x200,  1),
    'Pride Rock Map'       :(    True,    False,    currentType,     0x0FC,  1),
    'Oasis Map'       :(    True,    False,    currentType,     0x1FF,  1),
    'Undersea Kingdom Map'       :(    True,    False,    currentType,     0x07B,  1),
    'Disney Castle Map'       :(    True,    False,    currentType,     0x077,  1),
    'Cornerstone Hill Map'       :(    True,    False,    currentType,     0x072,  1),
    'Window of Time Map'       :(    True,    False,    currentType,     0x206,  1),
    'Halloween Town Map'       :(    True,    False,    currentType,     0x0FA,  1),
    'Christmas Town Map'       :(    True,    False,    currentType,     0x1FD,  1),
    'Naval Map'       :(    True,    False,    currentType,     0x0FB,  1),
    'Isla De Muerta Map'       :(    True,    False,    currentType,     0x1FB,  1),
    'Ship Graveyard Map'       :(    True,    False,    currentType,     0x1FC,  1),
    'Pit Cell Area Map'       :(    True,    False,    currentType,     0x0FE,  1),
    'I/O Tower Map'       :(    True,    False,    currentType,     0x203,  1),
    'Central Computer Core Map'       :(    True,    False,    currentType,     0x204,  1),
    'Dark City Map'       :(    True,    False,    currentType,     0x100,  1),
    'Castle That Never Was Map'       :(    True,    False,    currentType,     0x218,  1),
}

blackListUniqueID_Item = {
}
missableItemListUniqueID_Item = {
    2:{ #Missable prologue stuff
        32:{219},
        0:{318,319},
        10:{224,225,226,227},
        14:{235,236},
        22:{234},
        15:{228,229,230},
        16:{231,232},
        9:{219,220,221,222,223},
        33:{220,219},
        17:{233}
    }
}